# Generated by Django 3.2.15 on 2022-10-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadgets',
            name='img',
            field=models.ImageField(default='aabbcc', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
